
poly := t_var^2 +23;
K := AlgebraicExtension(Rationals, poly, "alpha");
one := One(K);
zero := Zero(K);
alpha := RootOfDefiningPolynomial(K);

Q :=
    [
    [                83,   7/2*alpha+143/2,   7/2*alpha+143/2 ],
    [  -7/2*alpha+143/2,                83,   7/2*alpha+143/2 ],
    [  -7/2*alpha+143/2,  -7/2*alpha+143/2,                83 ]
    ]*one;

A :=
[ [  -31/4*alpha-179/4,  -17/2*alpha-109/2,   -9/2*alpha-131/2 ],
  [    47/4*alpha-73/4,    55/4*alpha-71/4,     29/2*alpha+7/2 ],
  [   -3/4*alpha+233/4,   -3/2*alpha+135/2,        -6*alpha+63 ] ]*one;


B :=
[ [        6*alpha+63,   3/2*alpha+135/2,   3/4*alpha+233/4 ],
  [   -29/2*alpha+7/2,  -55/4*alpha-71/4,  -47/4*alpha-73/4 ],
  [   9/2*alpha-131/2,  17/2*alpha-109/2,  31/4*alpha-179/4 ] ]*one;

C :=
[ [   133/2*alpha-927/2,   211/2*alpha-233/2,    91/2*alpha-257/2 ],
  [        67*alpha+455,   -29/2*alpha+999/2,        11*alpha+239 ],
  [  -227/2*alpha+281/2,  -187/2*alpha-479/2,        -52*alpha-36 ] ];

#gamma is generated by e3 and g4^-1, these elements are swapped by the involution
#since unitary_rep is not fail the homomorphism is well defined
unitary_rep := GroupHomomorphismByImages(gamma6, Group(A,B), [gamma6.1, gamma6.2], [A,B]);

GaloisConjugateEntry := function(x)
    local c, a, b;
    c := ExtRepOfObj(x);
    a := c[1];
    b := c[2];
    return a*one - b*alpha;
end;

GaloisConjugateMatrix := function(M)
    return List(M, row -> List(row, x -> GaloisConjugateEntry(x)));
end;

HermitianTranspose := function(M)
    return TransposedMat(GaloisConjugateMatrix(M));
end;

IsScalar3x3 := function(M)
    local x;
    x := M[1][1];
    return
        M[2][2] = x
        and M[3][3] = x
        and M[1][2] = 0*x
        and M[1][3] = 0*x
        and M[2][1] = 0*x
        and M[2][3] = 0*x
        and M[3][1] = 0*x
        and M[3][2] = 0*x;
end;

#run
#TransposedMat(A)*Q*GaloisConjugateMatrix(A)*Q^-1;
#TransposedMat(B)*Q*GaloisConjugateMatrix(B)*Q^-1;
#TransposedMat(C)*Q*GaloisConjugateMatrix(C)*Q^-1;